-- Oracle 12c Release 2 or later. Execute in an empty application schema.
-- DDL auto-commits; this script is not intended for repeated execution.

CREATE TABLE roles (
 id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
 name VARCHAR2(255 CHAR) NOT NULL UNIQUE CHECK(name IN ('admin','operator'))
);
CREATE TABLE users (
 id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
 username VARCHAR2(255 CHAR) NOT NULL UNIQUE,
 password_hash VARCHAR2(255 CHAR) NOT NULL,
 role_id NUMBER(19) NOT NULL REFERENCES roles(id),
 created_at TIMESTAMP(6) NOT NULL DEFAULT LOCALTIMESTAMP
);
CREATE TABLE zones (
 id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
 simulator_name VARCHAR2(255 CHAR) NOT NULL UNIQUE,
 co_level NUMBER CHECK(co_level >= 0),
 updated_at TIMESTAMP(6) NOT NULL DEFAULT LOCALTIMESTAMP
);
CREATE TABLE parking_spots (
 id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
 simulator_name VARCHAR2(255 CHAR) NOT NULL UNIQUE,
 zone_id NUMBER(19) NOT NULL REFERENCES zones(id),
 spot_type VARCHAR2(255 CHAR) NOT NULL CHECK(spot_type IN ('any','electric','accessible')),
 occupancy_status VARCHAR2(255 CHAR) NOT NULL DEFAULT 'free' CHECK(occupancy_status IN ('free','reserved','occupied')),
 health_status VARCHAR2(255 CHAR) NOT NULL DEFAULT 'normal' CHECK(health_status IN ('normal','broken','maintenance')),
 usage_count NUMBER(19) NOT NULL DEFAULT 0 CHECK(usage_count >= 0),
 updated_at TIMESTAMP(6) NOT NULL DEFAULT LOCALTIMESTAMP
);
CREATE TABLE devices (
 id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
 simulator_name VARCHAR2(255 CHAR) NOT NULL UNIQUE,
 device_type VARCHAR2(255 CHAR) NOT NULL CHECK(device_type IN ('gate','light','fan','entry_sensor','exit_sensor')),
 zone_id NUMBER(19) REFERENCES zones(id),
 group_name VARCHAR2(255 CHAR),
 operating_state VARCHAR2(255 CHAR),
 health_status VARCHAR2(255 CHAR) NOT NULL DEFAULT 'normal' CHECK(health_status IN ('normal','broken','maintenance')),
 usage_count NUMBER(19) CHECK(usage_count >= 0),
 runtime_seconds NUMBER(19) CHECK(runtime_seconds >= 0),
 updated_at TIMESTAMP(6) NOT NULL DEFAULT LOCALTIMESTAMP
);
CREATE TABLE parking_sessions (
 id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
 plate_number VARCHAR2(255 CHAR) NOT NULL,
 car_type VARCHAR2(255 CHAR) NOT NULL,
 parking_spot_id NUMBER(19) REFERENCES parking_spots(id),
 status VARCHAR2(255 CHAR) NOT NULL DEFAULT 'waiting' CHECK(status IN ('waiting','heading_to_spot','parked','awaiting_payment','ready_to_exit','departed','cancelled')),
 arrived_at TIMESTAMP(6) NOT NULL,
 parked_at TIMESTAMP(6),
 unparked_at TIMESTAMP(6),
 departed_at TIMESTAMP(6),
 parking_duration_seconds NUMBER(19) CHECK(parking_duration_seconds >= 0)
);
CREATE UNIQUE INDEX ux_active_plate ON parking_sessions(
 CASE WHEN status NOT IN ('departed','cancelled') THEN plate_number END
);
CREATE UNIQUE INDEX ux_active_spot ON parking_sessions(
 CASE WHEN status IN ('heading_to_spot','parked') THEN parking_spot_id END
);
CREATE INDEX sessions_arrival ON parking_sessions(arrived_at);
CREATE INDEX sessions_status ON parking_sessions(status);
CREATE INDEX sessions_plate ON parking_sessions(plate_number);
CREATE TABLE invoices (
 id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
 parking_session_id NUMBER(19) NOT NULL UNIQUE REFERENCES parking_sessions(id),
 billable_minutes NUMBER(19) NOT NULL CHECK(billable_minutes >= 0),
 rate_per_minute_minor NUMBER(19) NOT NULL CHECK(rate_per_minute_minor >= 0),
 amount_due_minor NUMBER(19) NOT NULL CHECK(amount_due_minor >= 0),
 status VARCHAR2(255 CHAR) NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','requested','paid','cancelled')),
 requested_at TIMESTAMP(6),
 paid_at TIMESTAMP(6)
);
CREATE TABLE payment_attempts (
 id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
 invoice_id NUMBER(19) NOT NULL REFERENCES invoices(id),
 external_payment_id VARCHAR2(255 CHAR) UNIQUE,
 reported_amount_minor NUMBER(19) CHECK(reported_amount_minor >= 0),
 verification_status VARCHAR2(255 CHAR) NOT NULL DEFAULT 'pending' CHECK(verification_status IN ('pending','valid','invalid')),
 received_at TIMESTAMP(6) NOT NULL DEFAULT LOCALTIMESTAMP,
 verified_at TIMESTAMP(6)
);
CREATE INDEX payments_invoice ON payment_attempts(invoice_id);
CREATE TABLE webhook_events (
 id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
 external_event_id VARCHAR2(255 CHAR) UNIQUE,
 event_type VARCHAR2(255 CHAR) NOT NULL,
 payload CLOB NOT NULL CHECK(payload IS JSON),
 occurred_at TIMESTAMP(6),
 received_at TIMESTAMP(6) NOT NULL DEFAULT LOCALTIMESTAMP,
 processing_status VARCHAR2(255 CHAR) NOT NULL DEFAULT 'pending' CHECK(processing_status IN ('pending','processed','failed')),
 processed_at TIMESTAMP(6),
 error_message VARCHAR2(4000 CHAR)
);
CREATE INDEX events_processing ON webhook_events(processing_status,received_at);
INSERT INTO roles(name) VALUES ('admin');
INSERT INTO roles(name) VALUES ('operator');
COMMIT;
